In [ ]:
import pandas as pd

#read in the data using pandas
df = pd.read_csv('alzheimer.csv')
df = df.drop(['SES','CDR'],axis=1)
df = df[df.Group != 'Converted']
mapping_MF = {'M': 0, 'F': 1}
df = df.replace({ 'M/F': mapping_MF})
df = df.dropna()

#check data has been read in properly
df.head()

Group  M/F  Age  EDUC  MMSE  eTIV   nWBV    ASF
0  Nondemented    0   87    14  27.0  1987  0.696  0.883
1  Nondemented    0   88    14  30.0  2004  0.681  0.876
2     Demented    0   75    12  23.0  1678  0.736  1.046
3     Demented    0   76    12  28.0  1738  0.713  1.010
4     Demented    0   80    12  22.0  1698  0.701  1.034

In [ ]:
#check number of rows and columns in dataset
df.shape

(334, 8)

In [ ]:
#create a dataframe with all training data except the target column
X = df.drop(columns=['Group'])

#check that the target variable has been removed
X.head()

M/F  Age  EDUC  MMSE  eTIV   nWBV    ASF
0    0   87    14  27.0  1987  0.696  0.883
1    0   88    14  30.0  2004  0.681  0.876
2    0   75    12  23.0  1678  0.736  1.046
3    0   76    12  28.0  1738  0.713  1.010
4    0   80    12  22.0  1698  0.701  1.034

In [ ]:
#separate target values
y = df['Group'].values

#view target values
y[0:5]

array(['Nondemented', 'Nondemented', 'Demented', 'Demented', 'Demented'],
      dtype=object)

In [30]:
from sklearn.model_selection import train_test_split

#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1, stratify=y)
from sklearn.neighbors import KNeighborsClassifier

# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 2)

# Fit the classifier to the data
knn.fit(X_train,y_train)

knn.score(X_test, y_test)

0.6417910447761194

In [28]:
#show first 5 model predictions on the test data
knn.predict(X_test)[0:5]

array(['Demented', 'Nondemented', 'Demented', 'Demented', 'Nondemented'],
      dtype=object)

In [29]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.6417910447761194

In [23]:
from sklearn.model_selection import cross_val_score
import numpy as np

#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=2)

#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, y, cv=5)

#print each cv score (accuracy) and average them
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

[0.53731343 0.55223881 0.62686567 0.6119403  0.54545455]
cv_scores mean:0.5747625508819538


In [ ]:
from sklearn.model_selection import GridSearchCV

#create new a knn model
knn2 = KNeighborsClassifier()

#create a dictionary of all values we want to test for n_neighbors
param_grid = {'n_neighbors': np.arange(1, 25)}

#use gridsearch to test all values for n_neighbors
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)

#fit model to data
knn_gscv.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [ ]:
#check top performing n_neighbors value
knn_gscv.best_params_

{'n_neighbors': 5}

In [ ]:
#check mean score for the 
#top performing value of n_neighbors
knn_gscv.best_score_

0.5926729986431478

In [7]:
import pandas as pd

#read in the data using pandas
df = pd.read_csv('alzheimer.csv')
df = df.drop(['SES','CDR'],axis=1)
df = df[df.Group != 'Converted']
mapping_MF = {'M': 0, 'F': 1}
df = df.replace({ 'M/F': mapping_MF})
df = df.dropna()

#check data has been read in properly
df.head()

#check number of rows and columns in dataset
df.shape

#create a dataframe with all training data except the target column
X = df.drop(columns=['Group'])

#check that the target variable has been removed
X.head()

y = df['Group'].values

from sklearn.model_selection import train_test_split

#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1, stratify=y)

from sklearn.neighbors import KNeighborsClassifier

# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 2)

# Fit the classifier to the data
knn.fit(X_train,y_train)

#show first 5 model predictions on the test data
knn.predict(X_test)[0:5]

#check accuracy of our model on the test data
knn.score(X_test, y_test)

from sklearn.model_selection import cross_val_score
import numpy as np

#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=2)

#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, y, cv=5)

#print each cv score (accuracy) and average them
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

from sklearn.model_selection import GridSearchCV

#create new a knn model
knn2 = KNeighborsClassifier()

#create a dictionary of all values we want to test for n_neighbors
param_grid = {'n_neighbors': np.arange(1, 25)}

#use gridsearch to test all values for n_neighbors
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)

#fit model to data
knn_gscv.fit(X, y)

#check top performing n_neighbors value
knn_gscv.best_params_
print(knn_gscv.nest_params_)
#check mean score for the top performing value of n_neighbors
knn_gscv.best_score_
print(knn_gscv.best_score_)

[0.53731343 0.59701493 0.59701493 0.55223881 0.51515152]
cv_scores mean:0.5597467209407507
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


0.5926729986431478